name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Run Jest tests"
        run: npm test

  deploy:
    needs: test
    name: "Minify JS"
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Auto Minify"
        uses: nizarmah/auto-minify@v3
        with:
          directory: "dist/azimuth.js"
          output: "dist"
          overwrite: false

      # Auto commits minified files to the repository
      - name: "Auto committing minified files"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Github Action: Auto Minified JS files"
  
  convert:
    needs: deploy
    name: "Converting to ESM"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Run Microbundle"
        run: npm run build

      - name: "Auto committing converted file"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Github Action: Converted file to ESM"